version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/runner"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/generator"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"